### ISSUE TITLE
Obscure BLT dependency leads to unnecessary drs:init:settings invokation

### ISSUE THREAD

**Issue by ekubovsky-webfirst** [acquia/drupal-recommended-settings#85]
**Describe the bug**
As BLT is being phased out, we entirely replaced BLT with other tools. DRS is one of such tools. In Acquia pipelines, when a composer finishes install command, DRS plugin kicks in and runs `drs:init:settings`, which in its turn adds the following files to the settings directory:
```
-r--r----- 1 www-data doigov2 1.5K Feb 26 19:19 default.includes.settings.php
-r--r----- 1 www-data doigov2 5.2K Feb 26 19:19 default.local.settings.php
-r--r----- 1 www-data doigov2 5.2K Feb 26 19:19 local.settings.php
```
Excerpt from the logs:
```
composer install --no-dev -o --no-ansi

...

 - Skip [web-root]/sites/development.services.yml: disabled
 - Append to [project-root]/.editorconfig from .overrides.editorconfig

No security vulnerability advisories found.

 > /mnt/tmp/local.prod/source/vendor/bin/drush drs:init:settings

 [success] Settings generated successfully for site 'default'.
 [notice] Hash salt already exists.

...
```

There is no place for these files on any environment other then local development.

**To Reproduce**
Run a simple Acquia pipeline with the following step included:
```
events:
  build:
    steps:
      - setup-env:
          type: script
          script:
            - composer clear-cache && composer install --no-dev -o --no-ansi
```

**Expected behavior**
The `drs:init:settings` command should not be executed automatically.

**Screenshots**
none

**Environment**
Acquia pipelines

**Additional context**
none
